version: "3"
services:
    # php-fpm
    findme-energy-app:
        build:
            context: php-fpm/
            dockerfile: php-fpm-debian.dockerfile
            args:
                - APP_USER=${APP_USER}
        container_name: findme-energy-app
        restart: unless-stopped
        tty: true
        working_dir: /usr/share/nginx/findme.local
        depends_on:
            - findme-energy-db
            - findme-energy-redis
            - findme-energy-mailhog
        environment:
            SERVICE_NAME: ${APP_SERVICE_NAME}
            SERVICE_TAGS: ${APP_SERVICE_TAGS}
            APP_USER: ${APP_USER}
            SSH_AUTH_SOCK: /ssh-agent
        volumes:
            - ../src:/usr/share/nginx/findme.local # code
            - $SSH_AUTH_SOCK:/ssh-agent # Forward local machine SSH key to docker for ssh access to container
            - ./nginx/certs/:/certs/ # ssl certs
        #     - ./php-fpm/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini
        #   extra_hosts: # extra parameter for xdebug to work on linux/mac
        #     - "host.docker.internal:host-gateway"
        networks:
            - findme-energy-network

    # The Cache
    findme-energy-redis:
        image: redis:latest
        container_name: findme-energy-redis
        environment:
            SERVICE_NAME: ${CACHE_SERVICE_NAME}
            SERVICE_TAGS: ${CACHE_SERVICE_TAGS}
        volumes:
            - ${CACHE_VOLUME}:/var/lib/redis
        ports:
            - "6379:6379"
        networks:
            - findme-energy-network

    # PostgreSQL Service
    findme-energy-db:
        image: postgres:latest
        container_name: findme-energy-db
        restart: unless-stopped
        tty: true
        ports:
            - "5555:5432"
        environment:
            POSTGRES_DB: ${DB_NAME}
            POSTGRES_USER: ${DB_USER}
            POSTGRES_PASSWORD: ${DB_PASS}
            SERVICE_TAGS: ${DB_SERVICE_TAGS}
            SERVICE_NAME: ${DB_SERVICE_NAME}
#            PGDATA: ${DB_PATH_ON_CONTAINER} # Bit of a hack to get past the config file being written here before the data is written on build
        volumes:
            - ${DB_VOLUME}:/var/lib/postgresql/data
#            - ./postgresql/pg_hba.conf:/var/lib/postgresql/pg_hba.conf # TODO - decide what to do here
#            - ./postgresql/postgresql.conf:/var/lib/postgresql/postgresql.conf # TODO - decide what to do here
        networks:
            - findme-energy-network

    # Mailhog email catchall
    findme-energy-mailhog:
        image: mailhog/mailhog:latest
        container_name: findme-energy-mailhog
        restart: unless-stopped
        tty: true
        logging:
            driver: "none" # disable logs
        ports:
            - "8025:8025"
            - "1025:1025"
        networks:
            - findme-energy-network

    # Nginx Service
    findme-energy-nginx:
        image: nginx:latest
        container_name: findme-energy-nginx
        restart: unless-stopped
        tty: true
        depends_on:
            - findme-energy-app
        environment:
            SERVICE_NAME: ${WEB_SERVICE_NAME}
            SERVICE_TAGS: ${WEB_SERVICE_TAGS}
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - ../src:/usr/share/nginx/findme.local # code
            - ./nginx/conf.d/:/etc/nginx/conf.d/ # site conf
            - ./nginx/certs/:/etc/nginx/certs/ # ssl certs
        networks:
            - findme-energy-network


# Docker Networks
networks:
    findme-energy-network:
        driver: bridge
